{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flowforge.fullname" . }}
  labels:
    {{- include "flowforge.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-user: {{ .Values.secrets.postgres.user | quote }}
  postgres-password: {{ .Values.secrets.postgres.password | quote }}
  database-url: {{ include "flowforge.databaseURL" . | quote }}
  redis-url: {{ include "flowforge.redisURL" . | quote }}
  jwt-secret: {{ .Values.secrets.jwtSecret | quote }}
  encryption-key: {{ .Values.secrets.encryptionKey | quote }}
{{- end }}
